### ISSUE TITLE
Adding asynchronous api is recommended.

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityTextureOps#5]
like this：
TextureOps.LoadImageAsync()

![image](https://user-images.githubusercontent.com/50401776/185736279-daa057d2-52fc-451e-9c8d-09f253cd8043.png)

If the picture is big, it will be special.

**Comment by yasirkula** [comment]
Thank you for the suggestion. This would be useful, I agree 💡  However, I've other issues in my backlog so this one is a low priority for the time being.

**Comment by yasirkula** [comment]
Please note that I've tested the latest release on Android only. If you have an iOS test device, I'd appreciate it if you could test the new function on iOS in your spare time.
