### ISSUE TITLE
Cannot save the picture to the root directory.

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityTextureOps#9]
TextureOps.SaveImage( _texture2D , “D:\2023-10-06-10-11-43.jpg”);
--
UnauthorizedAccessException: Access to the path "D:\" is denied.
System.IO.Directory.CreateDirectoriesInternal (System.String path)

**Comment by yasirkula** [comment]
If you comment out this line, does it work for this specific path? https://github.com/yasirkula/UnityTextureOps/blob/66623dae8df39a8ef31ef0eb6fe340fbd744c007/Plugins/TextureOps/TextureOps.cs#L162

**Comment by ShenKang4181** [comment]
yes

**Comment by ShenKang4181** [comment]
can you update this Plugin?

**Comment by yasirkula** [comment]
I'll investigate this issue further and then hopefully push an update, yeah.
